### ISSUE TITLE
How to disable multi-touch on Ubuntu/non-parametric IPTSD?

### ISSUE THREAD

**Issue by horvathcsabalaszlo** [linux-surface/iptsd#82] opened 2022-09-27 14:55 UTC
Hi,

I have a KDE Neon-based Surface, and have issues with multi-touch IPTSD (ghost touches). (Basically Ubuntu 20.04.)

If i issue systemctl stop iptsd, touch is disabled. But i want to disable multi-touch, as the basic touch mode works flawlessly. 

I have read about a forked iptsd, and parametric service, but how can i install them?

Thanks,

**Comment by NP-chaonay** [comment] 2022-09-27 15:43
first of all

1) what is your surface model

**Comment by horvathcsabalaszlo** [comment] 2022-09-27 15:45
Pro 4.

**Comment by NP-chaonay** [comment] 2022-10-02 10:54
@horvathcsabalaszlo 

sorry for late response

could you try these two thing

1) recompiled linux-surface/intel-precise-touch from github
2) recompiled iptsd from github or get prebuilt pkg of the iptsd  from github

**Comment by horvathcsabalaszlo** [comment] 2022-10-02 11:13
> @horvathcsabalaszlo
> 
> sorry for late response
> 
> could you try these two thing
> 
> 1. recompiled linux-surface/intel-precise-touch from github
> 2. recompiled iptsd from github or get prebuilt pkg of the iptsd  from github

Thanks! 
Can you please show the correct Github link? I think the instructions should be there

**Comment by NP-chaonay** [comment] 2022-10-02 14:18
> > @horvathcsabalaszlo
> > sorry for late response
> > could you try these two thing
> > 
> > 1. recompiled linux-surface/intel-precise-touch from github
> > 2. recompiled iptsd from github or get prebuilt pkg of the iptsd  from github
> 
> Thanks! Can you please show the correct Github link? I think the instructions should be there

1)
https://github.com/linux-surface/intel-precise-touch at ```Building (DKMS)``` (dkms is recommended for general case)

2)
https://github.com/linux-surface/iptsd

**Comment by horvathcsabalaszlo** [comment] 2022-10-02 14:30
Thanks! Will try and come back.

**Comment by horvathcsabalaszlo** [comment] 2022-10-23 16:18
Sorry for delay, i had several other problems to deal with.

So installed iptsd from Github (from linux-surface/iptsd) and the only thing i got is

```
$ sudo ./build/src/daemon/iptsd /dev/hidraw0
[18:14:39.771] [error] No display config for this device was found!
```
No surprise it does not work :D (I stopped the original iptsd built in KDE neon, even tried to uninstall it and have the Git version installed with ninja, no success)

Tried to install latest Github-action .deb, but it has dependencies i cannot resolve. 

So i still need the method for disable the multi-touch... :D

**Comment by horvathcsabalaszlo** [comment] 2022-10-23 16:41
I installed a 2 month-old Github-action version, but it's actually older than in the repo. And it does not work :D

**Comment by NP-chaonay** [comment] 2022-10-25 02:06
> sudo dmesg|grep hidraw

so only 1 hidraw in dmesg ?

@horvathcsabalaszlo

**Comment by horvathcsabalaszlo** [comment] 2022-10-25 04:26
Hi,

Yes :

$ sudo dmesg|grep hidraw
[sudo] password for user: 
[    1.599565] hid-generic 0018:045E:0915.0001: hidraw0: I2C HID v1.00 Device [MSHW0030:00 045E:0915] on i2c-MSHW0030:00

**Comment by StollD** [comment] 2022-10-29 09:57
Given that #91 is basically a duplicate of this, and the other one has more discussion, I am closing this one.

**Closed by StollD** 2022-10-29 09:57 UTC
